version: '3.4'

networks:
  net:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.30.30.0/24

volumes:
  logs:


services:
##
  svc1:
    image: svc1
    ports:
      - "80:80"
    networks:
      - net
    volumes:
      - logs:/var/log/app
    environment:
      - APP_ENV=qa
    labels:
      - aliyun.logs.svc1-stdout=stdout
      - aliyun.logs.svc1-file=/var/log/app/svc1.log
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
